### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by ReadingRocks145** [simongravelle/atb2lammps#1]
I'm trying to make the LAMMPS molecular files for 4-Cyano-4'-pentylbiphenyl. I made a new molecular folder called 5CB_C18H19N, then took the GROMOS_54A7_ATB.lt and 2XJB_allatom_optimized_geometry.lt and added them took the folder. When I run the executable script from the atb2lammps folder, I get the error: "OSError: [WinError 193] %1 is not a valid Win32 application" for line 24 of the code (run_moltemplate = , see image). The system.lt file was created successfully. I can fix this error by adding either shell=True or sys.executable to the command, but then I get a FileNotFound error for sys.in.settings in the next line (no_charge =, see image). According to the top of ATB files:

"The file `system.lt` can be converted to a LAMMPS input `system.in` and data file `system.data` with the following shell command, assuming that all three LT files `system.lt`, `GROMOS_54A7_ATB.lt` and `2XJB_allatom_optimized_geometry.lt` are located in the current directory"

In addition, the moltemplate manual says that running the moltemplate.sh command will make:

"Moltemplate will create the following files: “system.data”, “run.in.EXAMPLE”,
“system.in.init”, “system.in.settings”, (and possibly other files including
“system.in.coords”). "

So I'm assuming the files system.data and system.in.settings should have appeared after the run_moltemplate command. I'm not sure if my fix for the OSError is causing this problem, or it's something else. Thank you in advance!

![image](https://github.com/simongravelle/atb2lammps/assets/95380765/00959191-4051-4e21-8cbf-e8e2e20de068)
![image](https://github.com/simongravelle/atb2lammps/assets/95380765/2ba0ecd4-7b94-4657-b450-a5a8bd3b71e9)
![image](https://github.com/simongravelle/atb2lammps/assets/95380765/17f284ca-56ad-4c0e-925d-e00097919117)

**Comment by simongravelle** [comment]
I only tested atb2lammps on Linux, and I am not a Windows user myself, so I am afraid I can't help you with that one. See also this comment from the moltemplate website (https://www.moltemplate.org/): 

> Moltemplate requires the Bourne-shell, and a recent version of python (2.7 or 3.0 or higher), and can run on OS X, linux, or windows (if a suitable shell environment has been installed).

An easy fix may be to use a UNIX-like shell.
